# Dependabot configuration file
# See documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/nextjs-temp" # Location of package.json
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      # Ignore major version updates for these dependencies as they might require manual intervention
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
    groups:
      # Group together all minor and patch updates for React packages
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"