name: DocAnalyze CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel in-progress runs on new commits to same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: TypeScript & Next.js Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetching the whole history to compare changes
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5
      
      - name: Get changed TS/JS files
        id: changed-ts-files
        if: github.event_name == 'pull_request'
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRTUXB origin/${{ github.base_ref }} ${{ github.sha }} | grep -E '\.(js|jsx|ts|tsx)$' | xargs)" >> $GITHUB_OUTPUT
      
      - name: Run ESLint on changed files
        if: github.event_name == 'pull_request' && steps.changed-ts-files.outputs.files != ''
        run: |
          echo "Linting changed TS/JS files: ${{ steps.changed-ts-files.outputs.files }}"
          npx eslint ${{ steps.changed-ts-files.outputs.files }}
        timeout-minutes: 2
      
      - name: Run Next.js lint
        run: npx next lint
        timeout-minutes: 2
        
      - name: TypeScript type checking
        run: npx tsc --noEmit
        timeout-minutes: 2

  test:
    name: Jest Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Shallow clone for speed
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
      timeout-minutes: 5
      
    - name: Test frontend with Jest
      run: |
        npm test -- --coverage
      timeout-minutes: 5
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage-final.json
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build Next.js App
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Prisma
        run: npx prisma generate
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-