name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
          pip install pymdown-extensions
          pip install mkdocs-material-extensions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Debug MkDocs configuration
        run: |
          echo "MkDocs version:"
          mkdocs --version
          echo "Material theme version:"
          pip show mkdocs-material | grep Version
          echo "Available plugins:"
          pip list | grep mkdocs
      
      - name: Build documentation
        run: |
          mkdocs build --site-dir ./site --verbose
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          publish_branch: gh-pages
          enable_jekyll: false
          cname: ${{ secrets.CNAME }}