name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'requirements.txt'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetching all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      
      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material>=9.2.0
          pip install Pygments
          pip install pymdown-extensions
          pip install mkdocs-material-extensions
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Build and Deploy MkDocs
        run: |
          mkdocs build --verbose --clean
          
          # Create necessary files for GitHub Pages
          touch ./site/.nojekyll
          
          # Deploy to GitHub Pages
          cd site
          git init
          git add -A
          git commit -m "Deploy Documentation updates" || echo "No changes to commit"
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" main:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify Deployment
        run: |
          echo "Documentation has been deployed to GitHub Pages."
          echo "Please allow a few minutes for the changes to be visible at:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"